config/routes.rb
Tardis::Application.routes.draw do
  resources :task_rows

  resources :users

  resources :roles

  resources :tasks

  resources :days

  root :to => "users#index"

end

app/models/task_row.rb
class TaskRow < ActiveRecord::Base
  belongs_to :task
  has_many :day
end

app/controllers/task_rows_controller.rb
class TaskRowsController < ApplicationController
  # GET /task_rows
  # GET /task_rows.xml
  def index
    @task_rows = TaskRow.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @task_rows }
    end
  end

  # GET /task_rows/1
  # GET /task_rows/1.xml
  def show
    @task_row = TaskRow.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task_row }
    end
  end

  # GET /task_rows/new
  # GET /task_rows/new.xml
  def new
    @task_row = TaskRow.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task_row }
    end
  end

  # GET /task_rows/1/edit
  def edit
    @task_row = TaskRow.find(params[:id])
  end

  # POST /task_rows
  # POST /task_rows.xml
  def create
    @task_row = TaskRow.new(params[:task_row])

    respond_to do |format|
      if @task_row.save
        format.html { redirect_to(@task_row, :notice => 'Task row was successfully created.') }
        format.xml  { render :xml => @task_row, :status => :created, :location => @task_row }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task_row.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /task_rows/1
  # PUT /task_rows/1.xml
  def update
    @task_row = TaskRow.find(params[:id])

    respond_to do |format|
      if @task_row.update_attributes(params[:task_row])
        format.html { redirect_to(@task_row, :notice => 'Task row was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task_row.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /task_rows/1
  # DELETE /task_rows/1.xml
  def destroy
    @task_row = TaskRow.find(params[:id])
    @task_row.destroy

    respond_to do |format|
      format.html { redirect_to(task_rows_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/task_rows_helper.rb
module TaskRowsHelper
end

app/views/task_rows/_form.html.erb
<%= form_for(@task_row) do |f| %>
  <% if @task_row.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_row.errors.count, "error") %> prohibited this task_row from being saved:</h2>

      <ul>
      <% @task_row.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :startDate %><br />
    <%= f.date_select :startDate %>
  </div>
  <div class="field">
    <%= f.label :task %><br />
    <%= collection_select :task_row, :task_id, Task.all, "id", "project" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_rows/edit.html.erb
<h1>Editing task_row</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_row %> |
<%= link_to 'Back', task_rows_path %>

app/views/task_rows/index.html.erb
<h1>Listing task_rows</h1>

<table>
  <tr>
    <th>Start Date</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @task_rows.each do |task_row| %>
  <tr>
    <td><%= task_row.startDate %></td>
    <td><%= task_row.task.project if task_row.task %></td>
    <td><%= link_to 'Show', task_row %></td>
    <td><%= link_to 'Edit', edit_task_row_path(task_row) %></td>
    <td><%= link_to 'Destroy', task_row, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task row', new_task_row_path %>

app/views/task_rows/new.html.erb
<h1>New task_row</h1>

<%= render 'form' %>

<%= link_to 'Back', task_rows_path %>

app/views/task_rows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Startdate:</b>
  <%= @task_row.startDate %>
</p>

<p>
  <b>Task:</b>
  <%= @task_row.task.project if @task_row.task %>
</p>


<%= link_to 'Edit', edit_task_row_path(@task_row) %> |
<%= link_to 'Back', task_rows_path %>